### ISSUE TITLE
How do we implement this?

### ISSUE THREAD

**Issue by nduthoit** [probot/serverless-lambda#1]
HI @tcbyrd,

Thanks for putting this together. We've been trying to get a simple probot app (that performs a check on pull request description) working on lambda. We got it working locally with smee but we're at a dead end on how to deploy it to lambda. 
We've setup a new API in API Gateway and were able to test sending a payload to the lambda function. The issue is that the event handler defined in our app's index.js doesn't process the event and instead it gets processed by serverless-lambda (returns "Hello Node8!").

Could you provide a bit more information on how to get it working?

Thanks,

**Comment by tcbyrd** [comment]
Thanks for the bump @nduthoit! Sorry for the lack of docs. I'll work on that.

I have an example here that may help:

https://github.com/tcbyrd/invite-koa/blob/d206f5897eaa1bdca29d480e9a685bfb3ee8a31c/index.js#L1-L9

```javascript
const { serverless } = require('@probot/serverless-lambda')


const robot = (robot) => {
  robot.on('team.edited', async context => {
    context.log({context})
  })
}


module.exports.handler = serverless(robot)
```

If you're using "Hello Node8!", that indicates it received the event and didn't throw any errors. Did you get anything in Cloudwatch logs? There's a log statement right above that which would tell you what event it received:
https://github.com/probot/serverless-lambda/blob/f8aea8f677432dfd2575120f55342385148418a3/index.js#L53

I'm a little confused at your statement though. The index.js should be sending the event to serverless-lambda. Do you have any code I can look at?

**Comment by tcbyrd** [comment]
This is now published on npm. You can `npm install @probot/serverless-lambda` to add this to your probot app. Take a look at the new [README](https://github.com/probot/probot#probot) for more info on how to implement it. Definitely feel free to ask any clarifying questions!
