### ISSUE TITLE
npm package 0.2.0 has old files

### ISSUE THREAD

**Issue by mrchief** [probot/serverless-lambda#16]
I was getting `Error: Property `event` is deprecated, use `name`` but the [code](https://github.com/probot/serverless-lambda/blob/master/index.js#L55) seems to use the newer property. After a lot of head scratching, I checked the distributed files in the package and found the discrepancy:

![image](https://user-images.githubusercontent.com/781818/53853599-1ca81d00-3f94-11e9-8516-1b0f908e72fd.png)

**Comment by JasonEtco** [comment]
Yep, it looks like we haven't published a new release in a little. Will try to get on that soon!

**Comment by JasonEtco** [comment]
A few new releases have been published since this issue, including the recent 0.4.0. Thanks for the issue!
