### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by ksolie** [probot/serverless-lambda#23]
I am now seeing the following issue in CloudWatch in AWS and no changes have been made on the Lambda side nor the GitHub side. 

Andy ideas?

```
{
    "errorMessage": "Cannot convert undefined or null to object",
    "errorType": "TypeError",
    "stackTrace": [
        "Function.keys (<anonymous>)",
        "lowerCaseKeys (/var/task/node_modules/@probot/serverless-lambda/index.js:25:10)",
        "/var/task/node_modules/@probot/serverless-lambda/index.js:49:21"
    ]
}
```

**Comment by ksolie** [comment]
I'm no longer receiving the headers in the `event`

**Comment by ksolie** [comment]
Issue not related to serverless-lambda project

**Comment by oakbani** [comment]
@ksolie  How did you get this resolved? I see the same error while trying sample create-probot-app and deploying it to aws-lambda via serverless. 

This is my serverless.yml file
> functions:
  probot:
    handler: handler.probot

And this is handler.js


```

const { serverless } = require('@probot/serverless-lambda')
const appFn = require('./')
module.exports.probot = serverless(appFn)

```

**Comment by ksolie** [comment]
Did you correctly zip up the lambda?

**Comment by oakbani** [comment]
It automatically zips when I use serverless deploy

**Comment by pdoshiPANW** [comment]
I am facing same issue . How did you solve ?

**Comment by julioquintana** [comment]
tengo el mismo problema, como lo resolvieron??
