### ISSUE TITLE
Issue with serverless config for running probot on lambda

### ISSUE THREAD

**Issue by oakbani** [probot/serverless-lambda#28]
I am successfully running the standard sample create-probot-app locally and have integrated it with a github repo. Using this extension, I am trying to put this on lambda, but I continuously see this error message with multiple configuration tries. 

> {
>   "errorType": "TypeError",
>   "errorMessage": "Cannot convert undefined or null to object",
>   "trace": [
>     "TypeError: Cannot convert undefined or null to object",
>     "    at Function.keys (<anonymous>)",
>     "    at lowerCaseKeys (/var/task/node_modules/@probot/serverless-lambda/index.js:25:10)",
>     "    at Runtime.handler (/var/task/node_modules/@probot/serverless-lambda/index.js:49:21)",
>     "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)",
>     "    at process._tickCallback (internal/process/next_tick.js:68:7)"
>   ]
> }
> 

My serverless.yml is:

> service: serverless-my-first-app
> provider:
>   name: aws
>   runtime: nodejs10.x
> 
> functions:
>   probot:
>     handler: handler.probot
>     events:
>       - http: ANY /
>       - http: 'ANY {proxy+}'

This is my handler.js

> // handler.js
> const { serverless } = require('@probot/serverless-lambda')
> const appFn = require('./index.js')
> module.exports.probot = serverless(appFn)

**Comment by benoclock** [comment]
I also had this error when the request does not contains expected headers like `x-github-event`

How do you send your request ? GitHub Webhook ?

**Comment by mattcan** [comment]
With #48 merged, we can probably close this issue too @gr2m

**Comment by gr2m** [comment]
Aye, thank you @mattcan 👍🏼
