### ISSUE TITLE
Getting " at lowerCaseKeys (/var/task/node_modules/@probot/serverless-lambda/index.js:25:10)" error

### ISSUE THREAD

**Issue by jmunoz1992** [probot/serverless-lambda#34]
When I run `serverless invoke -f probot -l`, the serverless framework runs my lambda function and loads the first line of the app then fails due to the following error in the probot lambda index.js file:

![image](https://user-images.githubusercontent.com/34145731/73620721-b17a2700-45f8-11ea-912d-226a89bcfb6a.png)

I believe the error may be coming from this file: 

![image](https://user-images.githubusercontent.com/34145731/73620758-d9698a80-45f8-11ea-8c64-5ab67d79649c.png)

**Comment by alexdmejias** [comment]
@jmunoz1992 I have the same issue, did you have any luck resolving it?
