### ISSUE TITLE
Install probot/stale on this repo

### ISSUE THREAD

**Issue by oscard0m** [probot/serverless-lambda#42]
There are some issues open for a while, maybe could be interesting to install https://github.com/probot/stale here?

**Comment by gr2m** [comment]
we can do that, but I think it would be good for someone who is using `serverless-lambda` to go through the issues once and verify that they no longer apply, or check in with the authors to ask whether they still do

**Comment by dominguezcelada** [comment]
Not sure if I should tag tcbyrd and JasonEtco or wait for their triage of this issue

**Comment by gr2m** [comment]
there is no rush, let's wait
