### ISSUE TITLE
Upgrade to Probot v10

### ISSUE THREAD

**Issue by gr2m** [probot/serverless-lambda#43]
Hello Lambda friends,

we just released Probot v10 and I'd like to upgrade `@probot/serverless-lambda` for compatibility. Would any existing user/contributor would like to collaborate on that with me?

More importantly, I'd like to make this package obsolete with Probot v11. I'm not sure how it would look like, but making Probot play nicely with serverless environments is our priority for the next release. Please join the discussion at
https://github.com/probot/probot/issues/1286

**Comment by soberstadt** [comment]
I would love to see this happen too! I know two things that need to get updated are the imports in index.js:
https://github.com/probot/serverless-lambda/blob/52dafe0b84b117b97570b7c8add96552ff6e331b/index.js#L2-L3
to
```
const { resolve } = require('probot/lib/helpers/resolve-app-function')
const { findPrivateKey } = require('probot/lib/helpers/get-private-key')
```

**Comment by scolandrea** [comment]
Thanks, @soberstadt I just created a PR based on your recommendations :)
